<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="FluentValidation" Version="11.9.0" />
    <PackageReference Include="FluentValidation.DependencyInjectionExtensions" Version="11.9.0" />
    <PackageReference Include="MediatR" Version="12.2.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\TurboTaxi.Domain\TurboTaxi.Domain.csproj" />
    <ProjectReference Include="..\TurboTaxi.Models\TurboTaxi.Models.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="CQRS\Auth\Handlers\" />
    <Folder Include="CQRS\Users\Commands\Create\" />
  </ItemGroup>

</Project>
