// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TurboTaxi.Infrastructure.Data;

#nullable disable

namespace TurboTaxi.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260128111841_AddRefreshTokens")]
    partial class AddRefreshTokens
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("TurboTaxi.Domain.Entities.Driver", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedTime")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsVerified")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("UpdatedTime")
                        .HasColumnType("datetime2");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<int?>("VehicleId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.HasIndex("VehicleId");

                    b.ToTable("Drivers");
                });

            modelBuilder.Entity("TurboTaxi.Domain.Entities.DriverStatusHistory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("ChangedTime")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CreatedTime")
                        .HasColumnType("datetime2");

                    b.Property<int>("DriverId")
                        .HasColumnType("int");

                    b.Property<int>("NewStatus")
                        .HasColumnType("int");

                    b.Property<int>("OldStatus")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedTime")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("DriverId");

                    b.ToTable("DriverStatusHistories");
                });

            modelBuilder.Entity("TurboTaxi.Domain.Entities.Location", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AddressLine")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("City")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Country")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedTime")
                        .HasColumnType("datetime2");

                    b.Property<double>("Latitude")
                        .HasColumnType("float");

                    b.Property<double>("Longitude")
                        .HasColumnType("float");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedTime")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Locations");
                });

            modelBuilder.Entity("TurboTaxi.Domain.Entities.Notification", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedTime")
                        .HasColumnType("datetime2");

                    b.Property<int?>("DriverId")
                        .HasColumnType("int");

                    b.Property<bool>("IsRead")
                        .HasColumnType("bit");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("NotificationType")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ReadTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedTime")
                        .HasColumnType("datetime2");

                    b.Property<int?>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("DriverId");

                    b.HasIndex("UserId");

                    b.ToTable("Notifications");
                });

            modelBuilder.Entity("TurboTaxi.Domain.Entities.Payment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("CreatedTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ExternalTransactionId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("PaidTime")
                        .HasColumnType("datetime2");

                    b.Property<int>("PaymentMethod")
                        .HasColumnType("int");

                    b.Property<int>("PaymentStatus")
                        .HasColumnType("int");

                    b.Property<int>("RideId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedTime")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("RideId")
                        .IsUnique();

                    b.ToTable("Payments");
                });

            modelBuilder.Entity("TurboTaxi.Domain.Entities.PromoCode", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("DiscountType")
                        .HasColumnType("int");

                    b.Property<decimal>("DiscountValue")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<decimal?>("MaxDiscountAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("MaxUsageCount")
                        .HasColumnType("int");

                    b.Property<int?>("MaxUsagePerUser")
                        .HasColumnType("int");

                    b.Property<DateTime?>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("UpdatedTime")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("PromoCodes");
                });

            modelBuilder.Entity("TurboTaxi.Domain.Entities.Rating", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Comment")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedTime")
                        .HasColumnType("datetime2");

                    b.Property<int>("FromUserId")
                        .HasColumnType("int");

                    b.Property<int>("RideId")
                        .HasColumnType("int");

                    b.Property<int>("Stars")
                        .HasColumnType("int");

                    b.Property<int?>("ToDriverId")
                        .HasColumnType("int");

                    b.Property<int?>("ToUserId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedTime")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("FromUserId");

                    b.HasIndex("RideId");

                    b.HasIndex("ToDriverId");

                    b.HasIndex("ToUserId");

                    b.ToTable("Ratings");
                });

            modelBuilder.Entity("TurboTaxi.Domain.Entities.RefreshToken", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedTime")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsRevoked")
                        .HasColumnType("bit");

                    b.Property<string>("JwtId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("RevokedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedTime")
                        .HasColumnType("datetime2");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("RefreshTokens");
                });

            modelBuilder.Entity("TurboTaxi.Domain.Entities.Ride", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("AcceptedTime")
                        .HasColumnType("datetime2");

                    b.Property<double?>("ActualDistanceKm")
                        .HasColumnType("float");

                    b.Property<int?>("ActualDurationMinutes")
                        .HasColumnType("int");

                    b.Property<decimal?>("ActualFare")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime?>("CanceledTime")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("CompletedTime")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CreatedTime")
                        .HasColumnType("datetime2");

                    b.Property<decimal?>("DiscountAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("DriverId")
                        .HasColumnType("int");

                    b.Property<int>("EndLocationId")
                        .HasColumnType("int");

                    b.Property<double?>("EstimatedDistanceKm")
                        .HasColumnType("float");

                    b.Property<int?>("EstimatedDurationMinutes")
                        .HasColumnType("int");

                    b.Property<decimal?>("EstimatedFare")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("PaymentId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("PickUpTime")
                        .HasColumnType("datetime2");

                    b.Property<int?>("PromoCodeId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("RequestedTime")
                        .HasColumnType("datetime2");

                    b.Property<int>("RequestedVehicleType")
                        .HasColumnType("int");

                    b.Property<string>("RoutePolyline")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("StartLocationId")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<int?>("TariffId")
                        .HasColumnType("int");

                    b.Property<int?>("TariffId1")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedTime")
                        .HasColumnType("datetime2");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("DriverId");

                    b.HasIndex("EndLocationId");

                    b.HasIndex("PromoCodeId");

                    b.HasIndex("StartLocationId");

                    b.HasIndex("TariffId");

                    b.HasIndex("TariffId1");

                    b.HasIndex("UserId");

                    b.ToTable("Rides");
                });

            modelBuilder.Entity("TurboTaxi.Domain.Entities.RideStatusHistory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ChangedByType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ChangedByUserId")
                        .HasColumnType("int");

                    b.Property<DateTime>("ChangedTime")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CreatedTime")
                        .HasColumnType("datetime2");

                    b.Property<int>("NewStatus")
                        .HasColumnType("int");

                    b.Property<int>("OldStatus")
                        .HasColumnType("int");

                    b.Property<int>("RideId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedTime")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("RideId");

                    b.ToTable("RideStatusHistories");
                });

            modelBuilder.Entity("TurboTaxi.Domain.Entities.Tariff", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("BaseFare")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("CancellationFee")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("CityKey")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("CountryCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("CreatedTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("DisplayCityName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("FreeKm")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("FreeMinutes")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<decimal>("MinimumFare")
                        .HasColumnType("decimal(18,2)");

                    b.Property<TimeSpan?>("NightEnd")
                        .HasColumnType("time");

                    b.Property<decimal?>("NightMultiplier")
                        .HasColumnType("decimal(18,2)");

                    b.Property<TimeSpan?>("NightStart")
                        .HasColumnType("time");

                    b.Property<decimal>("PricePerKm")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("PricePerMinute")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime?>("UpdatedTime")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ValidFrom")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ValidTo")
                        .HasColumnType("datetime2");

                    b.Property<int>("VehicleType")
                        .HasColumnType("int");

                    b.Property<decimal?>("WaitingPricePerMinute")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("CityKey", "CountryCode")
                        .IsUnique();

                    b.ToTable("Tariffs");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BaseFare = 180m,
                            CityKey = "moscow",
                            CountryCode = "RU",
                            CreatedTime = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DisplayCityName = "Москва",
                            IsActive = true,
                            MinimumFare = 350m,
                            PricePerKm = 28m,
                            PricePerMinute = 9m,
                            VehicleType = 0
                        },
                        new
                        {
                            Id = 2,
                            BaseFare = 160m,
                            CityKey = "saint_petersburg",
                            CountryCode = "RU",
                            CreatedTime = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DisplayCityName = "Санкт-Петербург",
                            IsActive = true,
                            MinimumFare = 320m,
                            PricePerKm = 25m,
                            PricePerMinute = 8m,
                            VehicleType = 0
                        },
                        new
                        {
                            Id = 3,
                            BaseFare = 130m,
                            CityKey = "yekaterinburg",
                            CountryCode = "RU",
                            CreatedTime = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DisplayCityName = "Екатеринбург",
                            IsActive = true,
                            MinimumFare = 280m,
                            PricePerKm = 22m,
                            PricePerMinute = 7m,
                            VehicleType = 0
                        },
                        new
                        {
                            Id = 4,
                            BaseFare = 130m,
                            CityKey = "novosibirsk",
                            CountryCode = "RU",
                            CreatedTime = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DisplayCityName = "Новосибирск",
                            IsActive = true,
                            MinimumFare = 280m,
                            PricePerKm = 22m,
                            PricePerMinute = 7m,
                            VehicleType = 0
                        },
                        new
                        {
                            Id = 5,
                            BaseFare = 120m,
                            CityKey = "kazan",
                            CountryCode = "RU",
                            CreatedTime = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DisplayCityName = "Казань",
                            IsActive = true,
                            MinimumFare = 260m,
                            PricePerKm = 20m,
                            PricePerMinute = 6m,
                            VehicleType = 0
                        },
                        new
                        {
                            Id = 6,
                            BaseFare = 120m,
                            CityKey = "krasnoyarsk",
                            CountryCode = "RU",
                            CreatedTime = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DisplayCityName = "Красноярск",
                            IsActive = true,
                            MinimumFare = 260m,
                            PricePerKm = 20m,
                            PricePerMinute = 6m,
                            VehicleType = 0
                        },
                        new
                        {
                            Id = 7,
                            BaseFare = 125m,
                            CityKey = "nizhny_novgorod",
                            CountryCode = "RU",
                            CreatedTime = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DisplayCityName = "Нижний Новгород",
                            IsActive = true,
                            MinimumFare = 270m,
                            PricePerKm = 21m,
                            PricePerMinute = 6m,
                            VehicleType = 0
                        },
                        new
                        {
                            Id = 8,
                            BaseFare = 120m,
                            CityKey = "chelyabinsk",
                            CountryCode = "RU",
                            CreatedTime = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DisplayCityName = "Челябинск",
                            IsActive = true,
                            MinimumFare = 260m,
                            PricePerKm = 20m,
                            PricePerMinute = 6m,
                            VehicleType = 0
                        },
                        new
                        {
                            Id = 9,
                            BaseFare = 115m,
                            CityKey = "ufa",
                            CountryCode = "RU",
                            CreatedTime = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DisplayCityName = "Уфа",
                            IsActive = true,
                            MinimumFare = 250m,
                            PricePerKm = 19m,
                            PricePerMinute = 6m,
                            VehicleType = 0
                        },
                        new
                        {
                            Id = 10,
                            BaseFare = 120m,
                            CityKey = "samara",
                            CountryCode = "RU",
                            CreatedTime = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DisplayCityName = "Самара",
                            IsActive = true,
                            MinimumFare = 260m,
                            PricePerKm = 20m,
                            PricePerMinute = 6m,
                            VehicleType = 0
                        },
                        new
                        {
                            Id = 11,
                            BaseFare = 125m,
                            CityKey = "rostov_on_don",
                            CountryCode = "RU",
                            CreatedTime = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DisplayCityName = "Ростов-на-Дону",
                            IsActive = true,
                            MinimumFare = 270m,
                            PricePerKm = 21m,
                            PricePerMinute = 6m,
                            VehicleType = 0
                        },
                        new
                        {
                            Id = 12,
                            BaseFare = 130m,
                            CityKey = "krasnodar",
                            CountryCode = "RU",
                            CreatedTime = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DisplayCityName = "Краснодар",
                            IsActive = true,
                            MinimumFare = 280m,
                            PricePerKm = 22m,
                            PricePerMinute = 7m,
                            VehicleType = 0
                        },
                        new
                        {
                            Id = 13,
                            BaseFare = 115m,
                            CityKey = "omsk",
                            CountryCode = "RU",
                            CreatedTime = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DisplayCityName = "Омск",
                            IsActive = true,
                            MinimumFare = 250m,
                            PricePerKm = 19m,
                            PricePerMinute = 6m,
                            VehicleType = 0
                        },
                        new
                        {
                            Id = 14,
                            BaseFare = 120m,
                            CityKey = "voronezh",
                            CountryCode = "RU",
                            CreatedTime = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DisplayCityName = "Воронеж",
                            IsActive = true,
                            MinimumFare = 260m,
                            PricePerKm = 20m,
                            PricePerMinute = 6m,
                            VehicleType = 0
                        },
                        new
                        {
                            Id = 15,
                            BaseFare = 125m,
                            CityKey = "perm",
                            CountryCode = "RU",
                            CreatedTime = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DisplayCityName = "Пермь",
                            IsActive = true,
                            MinimumFare = 270m,
                            PricePerKm = 21m,
                            PricePerMinute = 6m,
                            VehicleType = 0
                        },
                        new
                        {
                            Id = 16,
                            BaseFare = 120m,
                            CityKey = "volgograd",
                            CountryCode = "RU",
                            CreatedTime = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DisplayCityName = "Волгоград",
                            IsActive = true,
                            MinimumFare = 260m,
                            PricePerKm = 20m,
                            PricePerMinute = 6m,
                            VehicleType = 0
                        },
                        new
                        {
                            Id = 17,
                            BaseFare = 130m,
                            CityKey = "tyumen",
                            CountryCode = "RU",
                            CreatedTime = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DisplayCityName = "Тюмень",
                            IsActive = true,
                            MinimumFare = 280m,
                            PricePerKm = 22m,
                            PricePerMinute = 7m,
                            VehicleType = 0
                        },
                        new
                        {
                            Id = 18,
                            BaseFare = 115m,
                            CityKey = "saratov",
                            CountryCode = "RU",
                            CreatedTime = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DisplayCityName = "Саратов",
                            IsActive = true,
                            MinimumFare = 250m,
                            PricePerKm = 19m,
                            PricePerMinute = 6m,
                            VehicleType = 0
                        },
                        new
                        {
                            Id = 19,
                            BaseFare = 110m,
                            CityKey = "dagestan_avg",
                            CountryCode = "RU",
                            CreatedTime = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DisplayCityName = "Дагестан (orta)",
                            IsActive = true,
                            MinimumFare = 230m,
                            PricePerKm = 18m,
                            PricePerMinute = 5m,
                            VehicleType = 0
                        },
                        new
                        {
                            Id = 20,
                            BaseFare = 200m,
                            CityKey = "norilsk",
                            CountryCode = "RU",
                            CreatedTime = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DisplayCityName = "Норильск",
                            IsActive = true,
                            MinimumFare = 400m,
                            PricePerKm = 35m,
                            PricePerMinute = 12m,
                            VehicleType = 0
                        },
                        new
                        {
                            Id = 21,
                            BaseFare = 120m,
                            CityKey = "default_ru",
                            CountryCode = "RU",
                            CreatedTime = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DisplayCityName = "Russia Default",
                            IsActive = true,
                            MinimumFare = 260m,
                            PricePerKm = 20m,
                            PricePerMinute = 6m,
                            VehicleType = 0
                        });
                });

            modelBuilder.Entity("TurboTaxi.Domain.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedTime")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("TurboTaxi.Domain.Entities.UserFavoriteLocation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AliasName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedTime")
                        .HasColumnType("datetime2");

                    b.Property<int>("LocationId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedTime")
                        .HasColumnType("datetime2");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("LocationId");

                    b.HasIndex("UserId");

                    b.ToTable("UserFavoriteLocations");
                });

            modelBuilder.Entity("TurboTaxi.Domain.Entities.UserPromoCode", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<int>("PromoCodeId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedTime")
                        .HasColumnType("datetime2");

                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<DateTime?>("LastUsedTime")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("UpdatedTime")
                        .HasColumnType("datetime2");

                    b.Property<int>("UsedCount")
                        .HasColumnType("int");

                    b.HasKey("UserId", "PromoCodeId");

                    b.HasIndex("PromoCodeId");

                    b.ToTable("UserPromoCodes");
                });

            modelBuilder.Entity("TurboTaxi.Domain.Entities.Vehicle", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Brand")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PlateNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedTime")
                        .HasColumnType("datetime2");

                    b.Property<int>("VehicleType")
                        .HasColumnType("int");

                    b.Property<int>("Year")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Vehicles");
                });

            modelBuilder.Entity("TurboTaxi.Domain.Entities.Driver", b =>
                {
                    b.HasOne("TurboTaxi.Domain.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TurboTaxi.Domain.Entities.Vehicle", "Vehicle")
                        .WithMany("Drivers")
                        .HasForeignKey("VehicleId");

                    b.Navigation("User");

                    b.Navigation("Vehicle");
                });

            modelBuilder.Entity("TurboTaxi.Domain.Entities.DriverStatusHistory", b =>
                {
                    b.HasOne("TurboTaxi.Domain.Entities.Driver", "Driver")
                        .WithMany("StatusHistory")
                        .HasForeignKey("DriverId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Driver");
                });

            modelBuilder.Entity("TurboTaxi.Domain.Entities.Notification", b =>
                {
                    b.HasOne("TurboTaxi.Domain.Entities.Driver", "Driver")
                        .WithMany()
                        .HasForeignKey("DriverId");

                    b.HasOne("TurboTaxi.Domain.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId");

                    b.Navigation("Driver");

                    b.Navigation("User");
                });

            modelBuilder.Entity("TurboTaxi.Domain.Entities.Payment", b =>
                {
                    b.HasOne("TurboTaxi.Domain.Entities.Ride", "Ride")
                        .WithOne("Payment")
                        .HasForeignKey("TurboTaxi.Domain.Entities.Payment", "RideId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ride");
                });

            modelBuilder.Entity("TurboTaxi.Domain.Entities.Rating", b =>
                {
                    b.HasOne("TurboTaxi.Domain.Entities.User", "FromUser")
                        .WithMany("RatingsGiven")
                        .HasForeignKey("FromUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TurboTaxi.Domain.Entities.Ride", "Ride")
                        .WithMany("Ratings")
                        .HasForeignKey("RideId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TurboTaxi.Domain.Entities.Driver", "ToDriver")
                        .WithMany("RatingsReceived")
                        .HasForeignKey("ToDriverId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("TurboTaxi.Domain.Entities.User", "ToUser")
                        .WithMany("RatingsReceived")
                        .HasForeignKey("ToUserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("FromUser");

                    b.Navigation("Ride");

                    b.Navigation("ToDriver");

                    b.Navigation("ToUser");
                });

            modelBuilder.Entity("TurboTaxi.Domain.Entities.RefreshToken", b =>
                {
                    b.HasOne("TurboTaxi.Domain.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("TurboTaxi.Domain.Entities.Ride", b =>
                {
                    b.HasOne("TurboTaxi.Domain.Entities.Driver", "Driver")
                        .WithMany("Rides")
                        .HasForeignKey("DriverId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("TurboTaxi.Domain.Entities.Location", "EndLocation")
                        .WithMany("EndLocationRides")
                        .HasForeignKey("EndLocationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TurboTaxi.Domain.Entities.PromoCode", "PromoCode")
                        .WithMany("Rides")
                        .HasForeignKey("PromoCodeId");

                    b.HasOne("TurboTaxi.Domain.Entities.Location", "StartLocation")
                        .WithMany("StartLocationRides")
                        .HasForeignKey("StartLocationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TurboTaxi.Domain.Entities.Tariff", "Tariff")
                        .WithMany()
                        .HasForeignKey("TariffId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("TurboTaxi.Domain.Entities.Tariff", null)
                        .WithMany("Rides")
                        .HasForeignKey("TariffId1");

                    b.HasOne("TurboTaxi.Domain.Entities.User", "User")
                        .WithMany("Rides")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Driver");

                    b.Navigation("EndLocation");

                    b.Navigation("PromoCode");

                    b.Navigation("StartLocation");

                    b.Navigation("Tariff");

                    b.Navigation("User");
                });

            modelBuilder.Entity("TurboTaxi.Domain.Entities.RideStatusHistory", b =>
                {
                    b.HasOne("TurboTaxi.Domain.Entities.Ride", "Ride")
                        .WithMany("StatusHistory")
                        .HasForeignKey("RideId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ride");
                });

            modelBuilder.Entity("TurboTaxi.Domain.Entities.UserFavoriteLocation", b =>
                {
                    b.HasOne("TurboTaxi.Domain.Entities.Location", "Location")
                        .WithMany()
                        .HasForeignKey("LocationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TurboTaxi.Domain.Entities.User", "User")
                        .WithMany("FavoriteLocations")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Location");

                    b.Navigation("User");
                });

            modelBuilder.Entity("TurboTaxi.Domain.Entities.UserPromoCode", b =>
                {
                    b.HasOne("TurboTaxi.Domain.Entities.PromoCode", "PromoCode")
                        .WithMany("UserPromoCodes")
                        .HasForeignKey("PromoCodeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TurboTaxi.Domain.Entities.User", "User")
                        .WithMany("UserPromoCodes")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PromoCode");

                    b.Navigation("User");
                });

            modelBuilder.Entity("TurboTaxi.Domain.Entities.Driver", b =>
                {
                    b.Navigation("RatingsReceived");

                    b.Navigation("Rides");

                    b.Navigation("StatusHistory");
                });

            modelBuilder.Entity("TurboTaxi.Domain.Entities.Location", b =>
                {
                    b.Navigation("EndLocationRides");

                    b.Navigation("StartLocationRides");
                });

            modelBuilder.Entity("TurboTaxi.Domain.Entities.PromoCode", b =>
                {
                    b.Navigation("Rides");

                    b.Navigation("UserPromoCodes");
                });

            modelBuilder.Entity("TurboTaxi.Domain.Entities.Ride", b =>
                {
                    b.Navigation("Payment");

                    b.Navigation("Ratings");

                    b.Navigation("StatusHistory");
                });

            modelBuilder.Entity("TurboTaxi.Domain.Entities.Tariff", b =>
                {
                    b.Navigation("Rides");
                });

            modelBuilder.Entity("TurboTaxi.Domain.Entities.User", b =>
                {
                    b.Navigation("FavoriteLocations");

                    b.Navigation("RatingsGiven");

                    b.Navigation("RatingsReceived");

                    b.Navigation("Rides");

                    b.Navigation("UserPromoCodes");
                });

            modelBuilder.Entity("TurboTaxi.Domain.Entities.Vehicle", b =>
                {
                    b.Navigation("Drivers");
                });
#pragma warning restore 612, 618
        }
    }
}
